services:
  plain-bridge-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    expose:
      - "18888"
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  cache:
    image: "docker.io/library/redis:7.4"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD"
    entrypoint:
      - "/bin/sh"
    environment:
      REDIS_PASSWORD: "${CACHE_PASSWORD}"
    expose:
      - "6379"
    networks:
      - "aspire"
  messaging:
    image: "docker.io/library/rabbitmq:4.1-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${MESSAGING_PASSWORD}"
    expose:
      - "5672"
      - "15672"
    networks:
      - "aspire"
  identityserver-endpoint:
    image: "${IDENTITYSERVER_ENDPOINT_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${IDENTITYSERVER_ENDPOINT_PORT}"
      ConnectionStrings__elasticsearch: "http://elastic:${ELASTICSEARCH_PASSWORD}@elasticsearch:9200"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://plain-bridge-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "identityServer-endpoint"
    expose:
      - "${IDENTITYSERVER_ENDPOINT_PORT}"
    depends_on:
      elasticsearch:
        condition: "service_started"
    networks:
      - "aspire"
  api-endpoint:
    image: "${API_ENDPOINT_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${API_ENDPOINT_PORT}"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
      services__identityServer-endpoint__http__0: "http://identityServer-endpoint:${IDENTITYSERVER_ENDPOINT_PORT}"
      ConnectionStrings__elasticsearch: "http://elastic:${ELASTICSEARCH_PASSWORD}@elasticsearch:9200"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://plain-bridge-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "api-endpoint"
    expose:
      - "${API_ENDPOINT_PORT}"
    depends_on:
      cache:
        condition: "service_started"
      messaging:
        condition: "service_started"
      identityserver-endpoint:
        condition: "service_started"
      elasticsearch:
        condition: "service_started"
    networks:
      - "aspire"
  server-endpoint:
    image: "${SERVER_ENDPOINT_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${SERVER_ENDPOINT_PORT}"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      services__api-endpoint__http__0: "http://api-endpoint:${API_ENDPOINT_PORT}"
      ConnectionStrings__elasticsearch: "http://elastic:${ELASTICSEARCH_PASSWORD}@elasticsearch:9200"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://plain-bridge-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "server-endpoint"
    expose:
      - "${SERVER_ENDPOINT_PORT}"
    depends_on:
      cache:
        condition: "service_started"
      messaging:
        condition: "service_started"
      api-endpoint:
        condition: "service_started"
      elasticsearch:
        condition: "service_started"
    networks:
      - "aspire"
  client-endpoint:
    image: "${CLIENT_ENDPOINT_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${CLIENT_ENDPOINT_PORT}"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      services__server-endpoint__http__0: "http://server-endpoint:${SERVER_ENDPOINT_PORT}"
      ConnectionStrings__elasticsearch: "http://elastic:${ELASTICSEARCH_PASSWORD}@elasticsearch:9200"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://plain-bridge-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "client-endpoint"
    expose:
      - "${CLIENT_ENDPOINT_PORT}"
    depends_on:
      cache:
        condition: "service_started"
      messaging:
        condition: "service_started"
      server-endpoint:
        condition: "service_started"
      elasticsearch:
        condition: "service_started"
    networks:
      - "aspire"
  elasticsearch:
    image: "docker.io/library/elasticsearch:8.17.3"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "${ELASTICSEARCH_PASSWORD}"
    expose:
      - "9200"
      - "9300"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
